version: '3.4'

services:
  naive:
    image: ayako359/navieproxy:go1.23
    container_name: naiveproxy
    tty: true
    restart: unless-stopped
    ports:
      - <httpPort>:<httpPort>
      - <httpsPort>:<httpsPort>
    volumes:
      - ./data:/data
      - ./share:/root/.local/share
      <certVolumes>
      <certKeyVolumes>
    command: ["/bin/bash", "/data/entry.sh"]
