version: '3.4'

services:
  naive:
    image: registry.cn-hangzhou.aliyuncs.com/web_default/naiveproxy:go1.23-al
    container_name: naiveproxy
    tty: true
    restart: unless-stopped
    ports:
      - <httpPort>:<httpPort>
      - <httpsPort>:<httpsPort>
    volumes:
      - ./data:/data
      - ./share:/root/.local/share
      <certVolumes>
      <certKeyVolumes>
    command: ["/bin/bash", "/data/entry.sh"]
